### ISSUE TITLE
RuntimeError shapes mismatch

### ISSUE THREAD

**Issue by griegler** [apchenstu/TensoRF#2]
Great work! 
I just wanted to try it out on the NeRF synthetic Lego dataset, but got a `RuntimeError`.

Running `python train.py --expname lego --datadir ~/data/nerf/nerf_synthetic/lego` yields

```
Traceback (most recent call last):
  File "train.py", line 303, in <module>
    reconstruction(args)
  File "train.py", line 169, in reconstruction
    rgb_map, alphas_map, depth_map, weights, uncertainty = renderer(rays_train, tensorf, chunk=args.batch_size,
  File "/home/ubuntu/workspace/TensoRF/renderer.py", line 16, in OctreeRender_trilinear_fast
    rgb_map, depth_map = tensorf(rays_chunk, is_train=is_train, white_bg=white_bg, ndc_ray=ndc_ray, N_samples=N_samples)
  File "/home/ubuntu/anaconda3/envs/TensoRF/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/workspace/TensoRF/models/tensorBase.py", line 449, in forward
    valid_rgbs = self.renderModule(xyz_sampled[app_mask], viewdirs[app_mask], app_features)
  File "/home/ubuntu/anaconda3/envs/TensoRF/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/workspace/TensoRF/models/tensorBase.py", line 109, in forward
    rgb = self.mlp(mlp_in)
  File "/home/ubuntu/anaconda3/envs/TensoRF/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/TensoRF/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/TensoRF/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/TensoRF/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x102 and 105x128)
```

Did I miss something?

**Comment by griegler** [comment]
Thanks, this did solve the problem.

**Comment by andybak** [comment]
Can you update the readme as it still has the incorrect instructions.
