### ISSUE TITLE
Module plyfile missing from the dependencies?

### ISSUE THREAD

**Issue by paulmelis** [apchenstu/TensoRF#41]
Using the conda and pip setup commands from the readme leaves me with this error:

```
(TensoRF) snellius paulm@gcn37 11:52 ~/c/TensoRF$ python train.py --config configs/steps_with_stuff.txt 
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from renderer import *
  File "/gpfs/home4/paulm/c/TensoRF/renderer.py", line 5, in <module>
    from utils import *
  File "/gpfs/home4/paulm/c/TensoRF/utils.py", line 159, in <module>
    import plyfile
ModuleNotFoundError: No module named 'plyfile'
```

Add with `pip install plyfile` seems to fix the issues.

**Comment by apchenstu** [comment]
Yes, thanks!
