### ISSUE TITLE
Problem training on own blender dataset

### ISSUE THREAD

**Issue by HannahHaensen** [apchenstu/TensoRF#60]
Hey

I created a custom dataset with blender from the original blender files, I face to following issue:
```
Iteration 04000: train_psnr = 17.97 test_psnr = 0.00 mse = 0.016522:  13%|███████▍                                                | 4000/30000 [00:57<06:14, 69.49it/s]
Traceback (most recent call last):
  File "train.py", line 302, in <module>
    reconstruction(args)
  File "train.py", line 236, in reconstruction
    new_aabb = tensorf.updateAlphaMask(tuple(reso_mask))
  File "/home/phd/anaconda3/envs/TensoRF/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/phd/Documents/GitHub/TensoRF/models/tensorBase.py", line 337, in updateAlphaMask
    xyz_min = valid_xyz.amin(0)
IndexError: amin(): Expected reduction dim 0 to have non-zero size.
```

with both TensorCP and TensorVMSplit

**Comment by jywu511** [comment]
The same question, did you fix it?

**Comment by gbliao** [comment]
@HannahHaensen @jywu511 @apchenstu  Hi, I have the same problem. How did you solve it? @
